---
- name: A play that runs on the ansible host
  hosts: "{{ ansible_target }}"
  #hosts: localhost
  vars_files:
    - vars.yml
    - private.yml

  environment:
    SECRET_KEY_BASE: "{{ rails_secret }}"

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted

  tasks:
    - name: disable selinux
      become: yes
      replace: dest=/etc/selinux/config regexp='^SELINUX=enforcing' replace='SELINUX=disabled'
      tags: selinux

    #- name: restart selinux
    #  become: yes
    #  service: name=selinux state=restarted

  roles:
    - { role: fits, become: yes }
    - { role: druw }
    - { role: druw_admin_prod }
    - { role: redis, become: yes }
    #- { role: ffmpeg, tags: ffmpeg }
    - { role: postgresql, become: yes }
    - { role: tomcat }
    - { role: fedora, tags: ['fedora'] }
    - { role: solr, tags: ['solr'] }
    - { role: apache, tags: ['apache'] }
