---
- name: A play that runs on the ansible host
  hosts: "{{ ansible_target }}"
  #hosts: localhost
  vars_files:
    - vars-full.yml
    - private.yml

  roles:
    - { role: fits, become: yes, tags: ['fits']}
    - { role: druw-fullstack, become: yes, tags: ['druw'] }
    - { role: postgresql, become: yes, tags: ['postgres'] }
    - { role: redis, become: yes, tags: ['redis'] }
    #- { role: tomcat }
    - { role: fedora, become: true, tags: ['fedora'] }
    - { role: solr, tags: ['solr'] }
    - { role: apache, tags: ['apache'] }
