---
  - name: khanh temp fix for missing http-parser for epel nodejs
    become: yes
    yum: pkg=https://kickstart.lib.washington.edu/rpm_repo/druw/7/x86_64/http-parser-2.7.1-3.el7.x86_64.rpm state=present

  - name: Install hyrax dependencies
    become: yes
    yum: pkg={{ item }} state=latest
    with_items:
      - clamav
      - coreutils
      - gcc-c++
      - git
      - GraphicsMagick
      - ImageMagick-devel
      - libreoffice-headless
      - libreoffice
      - nodejs
      - poppler-utils
      - sqlite-devel

  - name: install ruby
    become: true
    yum: name=https://github.com/feedforce/ruby-rpm/releases/download/{{ ruby_version }}/ruby-{{ ruby_version }}-1.el7.centos.x86_64.rpm

  - name: install rails
    become: true
    gem: name=rails version={{ rails_version }} user_install=no

  - name: Bundle install
    #command: "bundle install --path vendor/bundle chdir={{ application_home }} creates={{ application_home }}/vendor/bundle"
    command: "bundle install --path vendor/bundle --without production chdir={{ application_home }}" 

  - name: Check if admin users role has been created
    stat: path="{{ application_home }}/db/migrate*_user_roles.rb"
    register: admin_user_role

  - name: Generate admin role
    command: "rails generate roles chdir={{ application_home }}"
    when: admin_user_role.stat.exists == False

  - name: Rake db
    command: "bundle exec rails db:migrate RAILS_ENV=development chdir={{ application_home }}"

  - name: whitelist the 10.0.2.2 network space in the Web Console config
    tags: whitelist
    blockinfile:
      dest: "{{ application_home }}/config/environments/development.rb"
      insertbefore: "end"
      block: |2
          class Application < Rails::Application
            config.web_console.whitelisted_ips = '10.0.2.2'
          end
